### ISSUE TITLE
Error in running epicseg.R segment

### ISSUE THREAD

**Issue by SamBuckberry** [lamortenera/epicseg#10]
I consistently get the below error when running epicseg.R segment on a file with 3 marks with 5 states. I have tried with 2 or 3 marks and 3-5 states with the same error occurring. The error occurs after the fitting model iterations.  
Please let me know if you have any insight in how to resolve this issue
```
reached the maximum number of iterations
producing report
Error in if (!all(apply(model$transP, 1, isProbVector))) stop("rows of model$transP must sum up to 1") :
  missing value where TRUE/FALSE needed
Calls: <Anonymous> ... <Anonymous> -> do.call -> <Anonymous> -> validateModel
Execution halted
```

**Comment by lamortenera** [comment]
Hi Sam, I finally managed to set some time aside to fix this issue. I am very sorry that it took so long, I am working in a company now so I am doing this as a "hobby".
  
I had a look at the source code, it seems like 1 of the states is not used by the model anymore and it becomes "redundant". This causes some divide-by-0 errors. I have some ideas about how to address this, I could just put some "don't care" values for that model. However, I am not yet completely sure that this is the issue. Would you be able to send me the smallest dataset and the simplest command that causes the error?

Thanks in advance.

**Comment by lamortenera** [comment]
Hi Sam, 

another user had your same problem. In his case, the problem was much simpler than I thought.

**The problem was that the regions used were one region per bin. EpiCSeg needs large regions, usually comprising several bins**

Otherwise EpiCSeg treats each region independently, and it cannot find observations to fit the
transition probabilities, because there are no consecutive bins. Moreover, each region will have its initial probabilities, so the model has a lot of parameters and EpiCSeg will dramatically overfit.

I see that for some applications it can be easier to work with one bin per region, but EpiCSeg cannot fit an HMM with such an input.

I did 2 things:
1. Improved the error message and make EpiCSeg fail before fitting.
2. Wrote a R code snippet to merge contiguous bins in a GenomicRanges object where each region is a single bin. The script is below. You can use it in conjunction with the `epicseg:::readRegions` and `epicseg:::writeRegions` private functions to modify your BED file.  Note, however, that
these "merged" regions can still be VERY fragmented and EpiCSeg will tend to overfit.


    merge_bins <- function(regions){
    	library(GenomicRanges)
    	# make vector that says which range should be merged with the previous
    	v1 = start(regions)
    	v2 = c(-1, end(regions))[1:length(regions)]
    	same_coords_as_prev = v1 == (v2 + 1)
    	cs = c(0, as.integer(seqnames(regions)))
    	same_chr_as_prev = diff(cs) == 0
    	new_range = !(same_coords_as_prev & same_chr_as_prev)
    	# make a factor based on boolean vector
    	f = cumsum(new_range)
    	# make grangeslist where each element should be merged into a region
    	reg_list = split(regions, f)
    	# merge and unlist
    	ret = unlist(reduce(reg_list))
    	# sanity checks
    	stopifnot(length(ret) == length(reg_list))
    	stopifnot(sum(as.numeric(width(regions))) == sum(as.numeric(width(ret))))
    	ret
    }


Could you please confirm that this was the issue so that we can close it?
Thanks!

**Comment by lamortenera** [comment]
As I received no response I'll close the issue.
