### ISSUE TITLE
Save Model after Segmentation

### ISSUE THREAD

**Issue by apastore** [lamortenera/epicseg#13]
Hi Alessandro,

I have question is possible to save the model after training on a set of sample/s signal tracks and then use the trained model on a reduced set of tracks? Let´s say I do not have for all sample one particular  track (H3K9m3) but still  would like to segment on it and accept to  have some undetermined segment where there missing information is relevant. (State 1 is define by presence of H3K4me3 and H3K27ac so the missing H3K9m3 is not relevant, but State 2 is define by H3K4me3 and H3K9m3 and absence of H3K27ac so this one will be undetermined.

Thanks!

**Comment by lamortenera** [comment]
Hi apastore,

EpiCSeg's model is specific for a set of histone marks, it is not possible to apply it to a different set, even if it is a subset of it. That's because the histone marks are not independent. You can train your model on the minimal set of histone marks shared by all experiments. 

Cheers,
Alessandro

**Comment by apastore** [comment]
Thanks!
