### ISSUE TITLE
Installing EpiCSeg on a Mac

### ISSUE THREAD

**Issue by uqfgaiti** [lamortenera/epicseg#4]
Following the installation guide on the manual I got an error during the installation of the dependancy 'kfoots' using R 3.2.1

![screen shot 2015-07-31 at 14 34 48](https://cloud.githubusercontent.com/assets/13582788/9001160/dbe9e342-3796-11e5-85c9-9b9d7d85cccd.png)

**Comment by lamortenera** [comment]
Ciao!
thanks for your message. I just learned that most R installations on mac, which use the clang compiler, do not support multithreading with the openMP library (which is the line "#include omp.h"). 
I tried to adapt the kfoots dependency so that it will compile in your machine, but you will not be able to use multiple threads. Can you try to replace the line:

     install_github("lamortenera/kfoots") 

to the line:

    install_github("lamortenera/kfoots", ref="macsupport") 

and then follow the installation instructions as before? I do not have a mac so I rely on you to know if it works. If it works I'll add the changes to the master branch, so that you don't have to type ref="macsupport" anymore.

Thanks again!
Ale

**Comment by uqfgaiti** [comment]
Hi Ale,

thanks for the quick reply.

I replaced the line you suggested and got this.

Thanks for help
Fede

[cid:390819A1-84DD-4E1B-8C7D-5BEAFEA86CCF@uq.edu.au]
On 31 Jul 2015, at 18:37, lamortenera <notifications@github.com<mailto:notifications@github.com>> wrote:


Ciao!
thanks for your message. I just learned that most R installations on mac, which use the clang compiler, do not support multithreading with the openMP library (which is the line "#include omp.h").
I tried to adapt the kfoots dependency so that it will compile in your machine, but you will not be able to use multiple threads. Can you try to replace the line:

 install_github("lamortenera/kfoots")


to the line:

install_github("lamortenera/kfoots", ref="macsupport")


and then follow the installation instructions as before? I do not have a mac so I rely on you to know if it works. If it works I'll add the changes to the master branch, so that you don't have to type ref="macsupport" anymore.

Thanks again!
Ale

**Comment by lamortenera** [comment]
Ciao,
can you try again? It was the same problem as before, it cannot compile functions dealing with multithreading. It should work now... (fingers crossed).

**Comment by uqfgaiti** [comment]
Got this. 

![screen shot 2015-07-31 at 20 44 42](https://cloud.githubusercontent.com/assets/13582788/9005865/18cd4d84-37c5-11e5-9e89-6e01194afa9d.png)

**Comment by lamortenera** [comment]
I am very sorry for this back and forth, if I had a mac I could test this more quickly. I did another change. Could you try again?

**Comment by uqfgaiti** [comment]
Hi Ale,

the installation gave me some warnings but I went ahead and it seems that all got installed correctly without any error. I will try and use the software now. 

I will let you know if there are other issues

Thanks for assistance
Federico
