### ISSUE TITLE
Segmentation with two normaliazed datasets - GRanges not on the same genomic regions

### ISSUE THREAD

**Issue by rtmag** [lamortenera/epicseg#8]
Hello Alessandro,

I am testing the "Non-canonical" features of epicseg, as in doing segmentation with two normaliazed datasets coming from different Cell Lines. 

The command I am using is:
```
epicseg segment -c CD133+:CD133_norm.Rdata -c CD36+:CD36_norm.Rdata \
-r CD36_refined_regions.bed -n 6 --maxiter 300 \
--prefix DIF_seg
```

However it is giving me this error message
```
Iteration:	53	log-likelihood:	-117621007	
Iteration:	54	log-likelihood:	-117621007	
Iteration:	55	log-likelihood:	-117621007	
Iteration:	56	log-likelihood:	-117621007	
Iteration:	57	log-likelihood:	-117621007	
Iteration:	58	log-likelihood:	-117621007	
Iteration:	59	log-likelihood:	-117621007	
producing report
Error in (function (segments, model, outdir = ".", prefix = "", colors = NULL,  : 
  GRanges not on the same genomic regions
Calls: <Anonymous> -> <Anonymous> -> do.call -> <Anonymous>
Execution halted
```

Thanks for the library, it is great!
Best,
R

**Comment by lamortenera** [comment]
Hi Roberto,
I wasn't able to reproduce the problem that you had. I would do the following:
1. can you let me know whether you using a mac? Wich version of Bioconductor and which 
2. can you run the following code inside R (using the same R installation as the one you used for epicseg) and confirm that you are getting the value TRUE for both method 1 and method 2?



         library(GenomicRanges)
         gr1 <- GRanges(seqnames = c("chr1", "chr1"), ranges = IRanges(c(7,13), width = c(3, 9)))
         gr2 <- GRanges(seqnames = c("chr1", "chr2"), ranges = IRanges(c(1, 4), width = c(3, 9)))
         glist <- GRangesList(gr1, gr2)
 
         # method 1
         ws <- sapply(glist, function(segm) {sum(as.numeric(width(segm)))})
         all(ws == ws[1])
 
         # method 2
         ws <- sum(as(width(glist), "CompressedNumericList"))
         all(ws == ws[1])


 
3. I did a small modification to EpiCSeg so that now it uses method 1 from the script above. Can you try to install it and tell me if now your issue disappears? To install it, do the following from inside R:
    

        library(devtools)
        install_github("lamortenera/epicseg", ref="hotfix") 
        

4. in case the issue does not disappear, can you run the same command that you showed and which causes the error, but adding the option  `--save_rdata` ? You should obtain an .Rdata file (even if the program crashes). I would like to have a look at it.

**Comment by rtmag** [comment]
Hello Alessandro,

As you guessed I was using my mac, here is the info:

```
R version 3.2.2 (2015-08-14) -- "Fire Safety"
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Bioconductor version 3.2 (BiocInstaller 1.20.0)
```
Both methods returned "TRUE" in my R session.

I updated epicseg with the fix and it worked great! It stopped at iteration 59 just because the log-likelihood value didn't change for the last 12 iterations.

Would you still like to have the rdata file?

Best,
Roberto

**Comment by lamortenera** [comment]
So after converging the report works fine and you don't get any error anymore?

**Comment by rtmag** [comment]
That's right, after the update the error is gone. Sorry for not being clear in my previous comment.

**Comment by lamortenera** [comment]
That's great :D
